export const Sostoyanie = [
  "Удовлетворительно",
  "Неудовлетворительно",
  "Присутствует",
  "Отсутствует",
]
export const Protocol11Data = {
  ocenkaUsloviy: "",
  ocenkaUsloviyZam: "",
  osmotrApparatnoy: "",
  osmotrApparatnoyZam: "",
  proverkaVhodDvery: "",
  proverkaVhodDveryZam: "",
  osmotrStoyki: "",
  osmotrStoykiZam: "",
  proverkaSoedineniy: "",
  proverkaSoedineniyZam: "",
  proverkaKrossa: "",
  proverkaKrossaZam: "",
  proverkaOsveshen: "",
  proverkaOsveshenZam: "",
  osmotrFiderov: "",
  osmotrFiderovZam: "",
  proverkaZazemlen: "",
  proverkaZazemlenZam: "",
  osmotrGidroizolyac: "",
  osmotrGidroizolyacZam: "",
  proverkaFundamenta: "",
  proverkaFundamentaZam: "",
  proverkaGrunta: "",
  proverkaGruntaZam: "",
  osmotrOgrazhdenia: "",
  osmotrOgrazhdeniaZam: "",
  osmotrTerritorii: "",
  osmotrTerritoriiZam: "",
  osmotrNaruzhSostoyan: "",
  osmotrNaruzhSostoyanZam: "",
  proverkaSostoyanLestnic: "",
  proverkaSostoyanLestnicZam: "",
  proverkaInzhenerKommukac: "",
  proverkaInzhenerKommukacZam: "",
  proverkaOkon: "",
  proverkaOkonZam: "",
  proverkaPol: "",
  proverkaPolZam: "",
  nalicieNeisOborud: "",
  nalicieNeisOborudZam: "",
  nalicieStoronOper: "",
  nalicieStoronOperZam: "",
}
